[package]
name = "todo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.32"
clap = { version = "4.5.2", features = ["derive"] }
crossterm = "0.27.0"
csv = "1.1"
